### ISSUE TITLE
[BUG] Curl Command in README.md Does Not Match Release Asset Naming Convention

### ISSUE THREAD

**Issue by victorolet** [eat-pray-ai/yutu#41]
**Describe the bug**
The following curl command results in a 404 error.

```bash 
curl -sSfL https://github.com/eat-pray-ai/yutu/releases/latest/download/yutu-linux-$(uname -m) -o /usr/local/bin/yutu
```
Output

```bash
curl -sSfL https://github.com/eat-pray-ai/yutu/releases/latest/download/yutu-linux-$(uname -m) -o /usr/local/bin/yutu
curl: (22) The requested URL returned error: 404
```

**To Reproduce**

Run the below command on local machine:

```bash 
curl -sSfL https://github.com/eat-pray-ai/yutu/releases/latest/download/yutu-linux-$(uname -m) -o /usr/local/bin/yutu
```

**Expected behavior**
On a system where uname -m outputs x86_64, the command attempts to download yutu-linux-x86_64. The download fails with a 404 error because no asset named yutu-linux-x86_64 exists in the release assets.

The command should correctly map the system architecture to one of the available release assets (e.g., yutu_0.9.7_linux_amd64) and successfully download the binary.

**Desktop**
OS: Ubuntu 24.04.1 LTS
Shell: bash 5.2.21
Architecture: x86_64

**Additional context**
- The current release assets use the naming convention yutu_<version>_linux_amd64 for the x86_64 architecture. However, the installation script assumes the file would be named yutu-linux-x86_64.
- Update the README.md to provide instructions that match the current release asset naming conventions.
- Alternatively, rename the release assets to align with the script, such as yutu-linux-x86_64.

Thank you for working on this needed project!

**Comment by OpenWaygate** [comment]
Hi @victorolet, thanks a lot for spotting this bug!
The naming convention changed due to the migration from [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator) to [GoReleaser](https://goreleaser.com/) in the pipeline.

I have updated the assets name for v0.9.7 and will try to fix the gap between readme and assets, thanks again!

**Comment by OpenWaygate** [comment]
oops, in Linux `uname -a` gives me `x86_64` instead of `amd64`. I think I have to add a shell script.

**Comment by OpenWaygate** [comment]
Please check the new method: https://github.com/eat-pray-ai/yutu?tab=readme-ov-file#linux

**Comment by victorolet** [comment]
Adding the shell script solves the problem. Works well now!

**Comment by victorolet** [comment]
Adding the shell script solves the problem. Works well now! Thank you for working on this!
